spring:
  kafka:
    bootstrap-servers: hadoop201:9092,hadoop202:9092,hadoop203:9092
  datasource:
    druid:
      url: jdbc:mysql://hadoop201:3306/supermarket
      username: root
      password: 11111